name: REBORN
favicon: null
layout_spectrum: 0.6439461263362318
typography_spectrum: 0.6776523590087891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58585a'
    - '#ffffff'
    - '#fbcd08'
    - '#c5c5c5'
    - '#818183'
  brandStrength: 0.7468413321767002
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.43735136999748647
purpose: []
