name: REBORN
favicon: null
layout_spectrum: 0.6439461263362318
typography_spectrum: 0.6776523590087891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7468413321767002
  lightness: 0.9435842488892376
  saturation: 0.11761635821312666
  rhythmicContrast: 0.43735136999748647
purpose: []
